port: 7935
socks-port: 7936
allow-lan: false
mode: rule
log-level: silent
proxies:
  - name: 专线|日本02解锁
    type: vmess
    server: ppy-jpv2.kunlun02dns.com
    port: 26007
    uuid: f5f26521-6dac-3b14-96b0-f1c7ad47746d
    alterId: 0
    cipher: auto
    udp: true
  - name: 专线|美国02解锁
    type: vmess
    server: ppy-usv2.kunlun02dns.com
    port: 26002
    uuid: f5f26521-6dac-3b14-96b0-f1c7ad47746d
    alterId: 0
    cipher: auto
    udp: true
  - name: 专线|台湾02解锁
    type: vmess
    server: ppy-twv2.kunlun02dns.com
    port: 26060
    uuid: f5f26521-6dac-3b14-96b0-f1c7ad47746d
    alterId: 0
    cipher: auto
    udp: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - 专线|日本02解锁
      - 专线|美国02解锁
      - 专线|台湾02解锁
rules:
  - MATCH,PROXY
