port: 7891
socks-port: 7892
allow-lan: false
mode: global
log-level: warning
proxies:
  - id: p_1770558159136_10_bgczd
    name: (2x)IEPL专线 香港2
    type: vmess
    server: dzgz.tcity8.monster
    port: 35212
    uuid: e1a98d14-8827-426f-893c-527301073e04
    alterId: 0
    cipher: auto
    network: tcp
    tls: false
    skip-cert-verify: true
    servername: ''
    raw: >-
      vmess://eyJ2IjoiMiIsInBzIjoiKDJ4KUlFUExcdTRlMTNcdTdlYmYgXHU5OTk5XHU2ZTJmMiIsImFkZCI6ImR6Z3oudGNpdHk4Lm1vbnN0ZXIiLCJwb3J0IjoiMzUyMTIiLCJpZCI6ImUxYTk4ZDE0LTg4MjctNDI2Zi04OTNjLTUyNzMwMTA3M2UwNCIsImFpZCI6IjAiLCJuZXQiOiJ0Y3AiLCJ0eXBlIjoibm9uZSIsImhvc3QiOiIiLCJwYXRoIjoiIiwidGxzIjoiIn0=
    _sourceUrl: >-
      http://8.209.231.35:6868/api/v1/client/subscribe?token=edd4aeb86315b8c9df3bc52dc9afa98c
    _clashName: (2x)IEPL专线 香港2
    latency: 168
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.77.110
      isp: Chinanet
      country: CN
      hosting: false
    quality: basic
    avgLatency: 273
    testedAt: '2026-02-10T15:06:05.751Z'
    testResults:
      excellent: 0
      good: 0
      basic: 2
      details:
        - name: Facebook
          url: http://www.facebook.com
          success: false
          time: 5012
          error: '502'
        - name: Twitter
          url: http://twitter.com
          success: false
          time: 5011
          error: '502'
        - name: YouTube
          url: http://www.youtube.com
          success: false
          time: 5012
          error: '502'
        - name: Google
          url: http://www.google.com/generate_204
          success: false
          time: 5011
          error: '502'
        - name: GitHub
          url: http://github.com
          success: false
          time: 5302
          error: '000'
        - name: Google204
          url: http://www.gstatic.com/generate_204
          success: true
          time: 175
          httpCode: '204'
        - name: Cloudflare
          url: http://cp.cloudflare.com/generate_204
          success: true
          time: 371
          httpCode: '204'
    tfo: false
    udp: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - (2x)IEPL专线 香港2
rules:
  - MATCH,PROXY
