port: 7912
socks-port: 7913
allow-lan: false
mode: rule
log-level: silent
proxies:
  - id: p_1771924959672_13_dnguj
    name: 🇯🇵日本高速02|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 4497
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.amazon.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:4497?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=c3HflLWDVDkPf9J5kD-R171i16fchUfyFz2SemIh2nc&sid=63795b1c&sni=www.amazon.com&servername=www.amazon.com&spx=%2F&fp=safari#%F0%9F%87%AF%F0%9F%87%B5%E6%97%A5%E6%9C%AC%E9%AB%98%E9%80%9F02%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: c3HflLWDVDkPf9J5kD-R171i16fchUfyFz2SemIh2nc
      short-id: 63795b1c
    client-fingerprint: safari
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇯🇵日本高速02|转发优化
    latency: 261
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 329
proxy-groups:
  - name: test
    type: select
    proxies:
      - 🇯🇵日本高速02|转发优化
rules:
  - MATCH,test
