port: 7901
socks-port: 7902
allow-lan: false
mode: global
log-level: silent
proxies:
  - name: 美国us_13
    type: vless
    server: 1002.kingfisher.top
    port: 10000
    tfo: true
    skip-cert-verify: true
    uuid: f333afdc-c0de-4194-9abb-c07f1008f181
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    servername: www.python.org
    reality-opts:
      public-key: xaL947o_X586spUQ-Q956KA7RnEeSAjeONwbAnonGTE
    client-fingerprint: edge
    id: p_1770553708812_49_kkpiv
    latency: 999
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - 美国us_13
rules:
  - MATCH,PROXY
