port: 7895
socks-port: 7896
allow-lan: false
mode: rule
log-level: silent
proxies:
  - id: p_1771924959672_14_bf55x
    name: 🇯🇵日本高速03|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 57801
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.apple.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:57801?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=kPkr66HPlRJbf8MArxyg3HYBF4kI7AG2wnmJcNpehUM&sid=c0049029&sni=www.apple.com&servername=www.apple.com&spx=%2F&fp=qq#%F0%9F%87%AF%F0%9F%87%B5%E6%97%A5%E6%9C%AC%E9%AB%98%E9%80%9F03%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: kPkr66HPlRJbf8MArxyg3HYBF4kI7AG2wnmJcNpehUM
      short-id: c0049029
    client-fingerprint: qq
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇯🇵日本高速03|转发优化
    latency: 252
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 305
  - id: p_1771924959672_13_dnguj
    name: 🇯🇵日本高速02|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 4497
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.amazon.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:4497?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=c3HflLWDVDkPf9J5kD-R171i16fchUfyFz2SemIh2nc&sid=63795b1c&sni=www.amazon.com&servername=www.amazon.com&spx=%2F&fp=safari#%F0%9F%87%AF%F0%9F%87%B5%E6%97%A5%E6%9C%AC%E9%AB%98%E9%80%9F02%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: c3HflLWDVDkPf9J5kD-R171i16fchUfyFz2SemIh2nc
      short-id: 63795b1c
    client-fingerprint: safari
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇯🇵日本高速02|转发优化
    latency: 261
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 329
  - id: p_1771924952977_8_jzui6
    name: 试用节点-台湾
    type: ss
    server: jry.izenny.com
    port: 27689
    cipher: chacha20-ietf-poly1305
    password: 97b47d74-551f-4185-848f-d0ce15e7a5ee
    raw: >-
      ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5N2I0N2Q3NC01NTFmLTQxODUtODQ4Zi1kMGNlMTVlN2E1ZWU@jry.izenny.com:27689#%E8%AF%95%E7%94%A8%E8%8A%82%E7%82%B9-%E5%8F%B0%E6%B9%BE
    _sourceUrl: >-
      https://bestti.whtjdasha.com/api/v1/client/subscribe?token=774597f05c65581c5473e6e8ce10a0a5
    _clashName: 试用节点-台湾
    latency: 305
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 325
  - id: p_1771924950536_8_uutm8
    name: 试用节点-台湾
    type: ss
    server: jry.izenny.com
    port: 27689
    cipher: chacha20-ietf-poly1305
    password: 524e981c-b91e-4a7d-aaec-5813acbda186
    raw: >-
      ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo1MjRlOTgxYy1iOTFlLTRhN2QtYWFlYy01ODEzYWNiZGExODY@jry.izenny.com:27689#%E8%AF%95%E7%94%A8%E8%8A%82%E7%82%B9-%E5%8F%B0%E6%B9%BE
    _sourceUrl: >-
      https://bestti.whtjdasha.com/api/v1/client/subscribe?token=790a36bb973f15586187b5f56332c427
    _clashName: 试用节点-台湾_1
    latency: 332
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 380
  - id: p_1771924959672_10_z2r5v
    name: 🇭🇰香港高速02|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 51456
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.amazon.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:51456?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=eaR8CotpIPO2dYW1-GN20e0yX-3qCM1tWGNsfDEcGWw&sid=2b3275a874d54df8&sni=www.amazon.com&servername=www.amazon.com&spx=%2F&fp=ios#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E9%AB%98%E9%80%9F02%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: eaR8CotpIPO2dYW1-GN20e0yX-3qCM1tWGNsfDEcGWw
      short-id: 2b3275a874d54df8
    client-fingerprint: ios
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇭🇰香港高速02|转发优化
    latency: 384
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 440
  - id: p_1771924959672_9_e3wma
    name: 🇭🇰香港高速01|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 27311
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: apple.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:27311?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=jhB4k7UOxD8lIyOIImQcEzLCdlrkSKpSBFl8zLa2LT4&sid=4f05f9baa833&sni=apple.com&servername=apple.com&spx=%2F&fp=qq#%F0%9F%87%AD%F0%9F%87%B0%E9%A6%99%E6%B8%AF%E9%AB%98%E9%80%9F01%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: jhB4k7UOxD8lIyOIImQcEzLCdlrkSKpSBFl8zLa2LT4
      short-id: 4f05f9baa833
    client-fingerprint: qq
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇭🇰香港高速01|转发优化
    latency: 394
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 451
  - id: p_1771924952977_10_hnrjv
    name: 试用节点-日本
    type: ss
    server: jry.izenny.com
    port: 29571
    cipher: chacha20-ietf-poly1305
    password: 97b47d74-551f-4185-848f-d0ce15e7a5ee
    raw: >-
      ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5N2I0N2Q3NC01NTFmLTQxODUtODQ4Zi1kMGNlMTVlN2E1ZWU@jry.izenny.com:29571#%E8%AF%95%E7%94%A8%E8%8A%82%E7%82%B9-%E6%97%A5%E6%9C%AC
    _sourceUrl: >-
      https://bestti.whtjdasha.com/api/v1/client/subscribe?token=774597f05c65581c5473e6e8ce10a0a5
    _clashName: 试用节点-日本
    latency: 457
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 3674
  - id: p_1771924943543_8_zbj42
    name: 🇺🇸 机场推荐:dafei.de 美国 10
    type: vless
    server: 135.84.73.130
    port: 443
    uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
    tls: true
    skip-cert-verify: true
    network: ws
    servername: sni.111000.v6.navy
    raw: >-
      vless://6202b230-417c-4d8e-b624-0f71afa9c75d@135.84.73.130:443?security=tls&type=ws&path=%2F%3Fed%3D2560%26Telegram%F0%9F%87%A8%F0%9F%87%B3%20%40WangCai2&host=sni.111000.v6.navy&sni=sni.111000.v6.navy&fp=chrome#%F0%9F%87%BA%F0%9F%87%B8%20%E6%9C%BA%E5%9C%BA%E6%8E%A8%E8%8D%90%3Adafei.de%20%E7%BE%8E%E5%9B%BD%2010
    ws-opts:
      path: /?ed=2560&Telegram🇨🇳 @WangCai2
      headers:
        Host: sni.111000.v6.navy
    _sourceUrl: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    _clashName: 🇺🇸 机场推荐:dafei.de 美国 10
    latency: 567
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 1125
  - id: p_1771924959672_15_ezcqu
    name: 🇺🇸美国高速04|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 6511
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.apple.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:6511?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=p_I0wbrFv4166QX2y1zmnRtFE29pkme6ze5xoW5mkgs&sid=aaf4e908&sni=www.apple.com&servername=www.apple.com&spx=%2F&fp=safari#%F0%9F%87%BA%F0%9F%87%B8%E7%BE%8E%E5%9B%BD%E9%AB%98%E9%80%9F04%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: p_I0wbrFv4166QX2y1zmnRtFE29pkme6ze5xoW5mkgs
      short-id: aaf4e908
    client-fingerprint: safari
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇺🇸美国高速04|转发优化
    latency: 589
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: 601
  - id: p_1771924959672_16_0l7wg
    name: 🇺🇸美国高速05|转发优化
    type: vless
    server: jpfast-3.up-pay.xyz
    port: 34705
    uuid: b13f9fa5-846c-4b31-889e-c1801d2fd266
    tls: true
    skip-cert-verify: true
    network: tcp
    servername: www.apple.com
    flow: xtls-rprx-vision
    raw: >-
      vless://b13f9fa5-846c-4b31-889e-c1801d2fd266@jpfast-3.up-pay.xyz:34705?mode=multi&security=reality&encryption=none&type=tcp&flow=xtls-rprx-vision&pbk=VylpE8evnde8qRnCDhllL5RL655_BwzT-CFgd_i4WiM&sid=db8c23&sni=www.apple.com&servername=www.apple.com&spx=%2F&fp=edge#%F0%9F%87%BA%F0%9F%87%B8%E7%BE%8E%E5%9B%BD%E9%AB%98%E9%80%9F05%7C%E8%BD%AC%E5%8F%91%E4%BC%98%E5%8C%96
    reality-opts:
      public-key: VylpE8evnde8qRnCDhllL5RL655_BwzT-CFgd_i4WiM
      short-id: db8c23
    client-fingerprint: edge
    _sourceUrl: https://jc10a1.lada.mom/s/fe7ebb99dd520f7a3a3c5def6c414d13
    _clashName: 🇺🇸美国高速05|转发优化
    latency: 594
    purityScore: 100
    purityInfo:
      score: 100
      ip: 182.245.204.190
      isp: Chinanet
      country: CN
      hosting: false
    localLatency: -1
proxy-groups:
  - name: PROXY
    type: url-test
    proxies:
      - 🇯🇵日本高速03|转发优化
      - 🇯🇵日本高速02|转发优化
      - 试用节点-台湾
      - 试用节点-台湾
      - 🇭🇰香港高速02|转发优化
      - 🇭🇰香港高速01|转发优化
      - 试用节点-日本
      - 🇺🇸 机场推荐:dafei.de 美国 10
      - 🇺🇸美国高速04|转发优化
      - 🇺🇸美国高速05|转发优化
    url: http://www.gstatic.com/generate_204
    interval: 300
rules:
  - MATCH,PROXY
